---
# alacritty defalut settings github link
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
env:
  TERM: xterm-256color

import:
  - ~/.config/alacritty/themes/themes/iterm.yaml

window:
  dimensions:
    columns: 160
    lines: 48

  padding:
    x: 2
    y: 2

  opacity: 0.8

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

  title: Alacritty

scrolling:
  history: 10000

  multiplier: 3

font:
  normal:
    family: "Hack Nerd Font"
    style: Regular

  bold:
    family: "Hack Nerd Font"
    style: Bold

  italic:
    family: "Hack Nerd Font"
    style: Regular Italic

  size: 14.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  save_to_clipboard: true

cursor:
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Always

  vi_mode_style:
    shape: Beam
    blinking: On

  # Cursor blinking interval in milliseconds.
  blink_interval: 500

  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - --login
    # - -l
    # - -c
    # - "zellij attach --index 0 --create"
    # using tmux
    # - "tmux a -t 0 || tmux -u"

key_bindings:
  # see: https://github.com/alacritty/alacritty/wiki/Keyboard-mappings
  # yamllint disable rule:braces
  - { key: F, mods: Command, chars: "\x1bf" }
  - { key: B, mods: Command, chars: "\x1bb" }
  - { key: D, mods: Command, chars: "\x1bd" }
  - { key: LBracket, mods: Control, chars: "\x1b" }
  - { key: Backslash, mods: Alt, chars: "\x5c" }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Semicolon, mods: Command|Shift, action: IncreaseFontSize }
  - { key: Minus, mods: Command|Shift, action: DecreaseFontSize }
  - { key: Return, mods: Command, action: ToggleSimpleFullscreen } # For those, coming from iTerm, here's Command + Enter to ToggleFullscreen
  - {
      key: Comma,
      mods: Command,
      command:
        { program: "sh", args: ["-c", "~/.config/alacritty/alacritty.yml"] },
    }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Space, mods: Alt, chars: " " }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left, mods: Alt, chars: "\x1bb" } # one word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # one word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
