---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  braces:
    level: warning
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    level: warning
    min-spaces-inside: 0
    max-spaces-inside: 1

  colons:
    level: warning

  commas: disable

  comments:
    level: warning
    min-spaces-from-content: 1

  comments-indentation: disable

  document-end: disable

  document-start:
    level: warning
  
  empty-lines: disable

  empty-values: disable

  hyphens:
    level: warning

  indentation:
    level: warning
    indent-sequences: consistent

  key-duplicates: enable

  key-ordering: disable

  line-length: disable

  new-line-at-end-of-file:
    level: warning

  new-lines: enable

  octal-values: disable

  trailing-spaces:
    level: warning

  truthy: disable
