---
default_mode: locked
pane_frames: false
scrollback_editor: /usr/bin/mcedit
keybinds:
  locked:
    - unbind: true
    - action: [SwitchToMode: Normal,]
      key: [Ctrl: 'a',]
    - action: [MoveFocusOrTab: Left,]
      key: [ Alt: 'h', Alt: Left]
    - action: [MoveFocusOrTab: Right,]
      key: [ Alt: 'l', Alt: Right]
    - action: [MoveFocus: Down,]
      key: [ Alt: 'j', Alt: Down]
    - action: [MoveFocus: Up,]
      key: [ Alt: 'k', Alt: Up]
window:
  option_as_alt: Both
